### ISSUE TITLE
Proposal: JSON all the things

### ISSUE THREAD

**Issue by jmar777** [chstechcommunity/people#16]
This idea may be moot as I'm not sure what the grander vision is here, but I wanted to suggest the following:
- Instead of individual repos for people, companies, etc., move everything into a GitHub pages repo (i.e., chstechcommunity.github.io), where each individual list becomes a distinct file.
- Each of these files would in turn be converted into a structured JSON file, using a known set of keys.  E.g.,:

```
[
  {
    "displayName": "Tom Wilson",
    "githubUsername": "twilson63",
    "twitterUsername": "twilson63"
  },
  {
    "displayName": "Jeremy Martin",
    "githubUsername": "jmar777",
    "twitterUsername": "jmar777"
  },
  ...
]
```

**Motivation:** because GitHub Pages now implicitly set CORS headers that allow access from anywhere, this could become a repo that would be useful for little mashup apps (e.g., a chstech twitter slack bot, a news feed for all chstech GH activity, etc.).  While there may be some level of novelty/usefulness there by itself, I think it could further be useful as a primitive API for local meetups and developer classes, wherein students/attendees would be able to interact with some slightly more contextual data (albeit in a readonly fashion).

Thoughts?

**Comment by twilson63** [comment]
@jmar777 imo all ideas are welcome here, the only grand vision is to have an index of the tech community that can be managed by the community, so that other sources may pull from, without being controlled by any one entity, i am happy to provide full ownership rights to all that want to see this community grow and sustain.

As far as your suggestion I think it is a great idea, @rgc had some similar thoughts, I would encourage others to weigh in as well. if this catches on and json all the things is the best way to sustain and provide value I will be happy to work on a conversion.

i took this approach mainly following examples like nodebots and the nodejs community organizing patterns, and to make it engaging to all, with the requirement of being capable of submitting a pull request. :)

**Comment by jmar777** [comment]
@twilson63 That's a good point (re: avoiding barriers like git-specific familiarity). I just did a quick test on another repo, and it looks like the GitHub web UI allows editing JSON (and most other) file types as well, without any need for command line forking/pulling/pushing/etc., so maybe that's still an option?

I'm not too familiar with what nodebots and similar have done previously, though (I just remember when the node wiki used to actually catalog modules, lol...), so if there's some precedence and reasoning behind the current solution that's all good too. Just thinking out loud. 🤔

**Comment by rgc** [comment]
@jmar777 - yes, this is a good idea...  i won't have time until the weekend, but i'm going to throw together a jekyll template that will generate per-user pages...   I use yaml for my personal page, but json would be fine as well:

```
users:
 rgc:
  name: Rob Colantuoni
  email: rgc@colantuoni.com
  #tagline: "something interesting"
  # gravatar hash of email address
  gravatar: f3cebd26d058b00d6922f969c8f7d61d
  social:
    github: rgc
    twitter: rgc
    linkedin: robcolantuoni
    keybase: rgc
    #gplus: +RobertColantuoni
    #aboutme:
    #bitbucket:
    #hacker_news: 
    #stackexchange:
    #stackoverflow:
    #facebook:
    #tumblr:
```

@twilson63 - these user configs can also be used to generate consumable formats such as RSS, JSON, XML, etc... so that integration isn't affected.
